### ISSUE TITLE
Why all results are -1?

### ISSUE THREAD

**Issue by Med-Process** [360CVGroup/OVD_Contest#10]
I have visualized results of test set with our model, and submit the reuslt. But, I got all metrics of -1:
![image](https://github.com/360CVGroup/OVD_Contest/assets/57434913/dd767ac9-38ba-4713-b6a2-51300e07313a)

I checked the image ID, which is correct with the "test.json". 
![image](https://github.com/360CVGroup/OVD_Contest/assets/57434913/68ef5e8f-8357-4048-a6a7-2c077007764c)

Any other problems?

Thanks!

**Comment by binwang777** [comment]
Hi, first of all, the way to compress the file should be: right mouse click on the Json file and compress it directly as a zip file. Your latest submitted file is correct. 
Secondly, by manually checking the Json file you submitted, we found that the end of the list is missing at the internal end, the specific error is as follows:
![image](https://github.com/360CVGroup/OVD_Contest/assets/32870325/f0d94a40-4105-4b72-82e6-d880d1e089ee)

**Comment by Med-Process** [comment]
Thanks for your reply!
