### ISSUE TITLE
请问能不能更改队伍名字

### ISSUE THREAD

**Issue by jirufengyu** [360CVGroup/OVD_Contest#12]

**Comment by jirufengyu** [comment]
@binwang777 wenyoupeng0@outlook.com 改成sysuabcd，谢谢

**Comment by binwang777** [comment]
> @binwang777 [wenyoupeng0@outlook.com](mailto:wenyoupeng0@outlook.com) 改成sysuabcd，谢谢

你好，没有查询到[wenyoupeng0@outlook.com](mailto:wenyoupeng0@outlook.com)，是854725760@qq.com或youpeng_wen@163.com吗

**Comment by jirufengyu** [comment]
@binwang777 麻烦再改一下邮箱是wenyoupeng0@outlook.com, 改成sysu_zhigong, 谢谢

**Comment by binwang777** [comment]
> @binwang777 麻烦再改一下邮箱是[wenyoupeng0@outlook.com](mailto:wenyoupeng0@outlook.com), 改成sysu_zhigong, 谢谢

已改

**Comment by jirufengyu** [comment]
@binwang777 请问，用一个邮箱申请了多个账号，只按邮箱不能索引到对应的队伍

**Comment by binwang777** [comment]
uuid是唯一的，对应一个队名。如果你需要再次更改名称，请将你的uuid与改的名字发送到以下邮箱：17093040353@163.com。

**Comment by binwang777** [comment]
修改名称问题，请发送信息到[17093040353@163.com](mailto:17093040353@163.com)
