### ISSUE TITLE
Results of July 4th Not Updated

### ISSUE THREAD

**Issue by wusize** [360CVGroup/OVD_Contest#15]
It seems that the test results of July 4th failed to be released. Is there anything wrong with the evaluation server? And how long do we need to wait for the results? It's discouraging that we cannot get feedback on time.

**Comment by binwang777** [comment]
Hi, because the file size submitted by a team reached about 1G, which caused a delay in the test evaluation process. We will manually test this file, and the test results of the rest of the files will be sent to the player's mailbox within 1 hour, and the leaderboard will be updated.

**Comment by wusize** [comment]
Ok. Thanks for your kind response!

**Comment by binwang777** [comment]
Hi, the update has been completed, now you can see the latest ranking!
