### ISSUE TITLE
结果上传疑问

### ISSUE THREAD

**Issue by msbrm** [360CVGroup/OVD_Contest#5]
对于novel类别的物体在上传结果时候应该填写什么类别呢

<img width="812" alt="image" src="https://user-images.githubusercontent.com/112378987/232776516-f2eb94ab-443c-4a73-9997-3a719ef48e13.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/112378987/232776294-a984464c-5383-4aa3-8e76-f73f3ed5f467.png">

**Comment by SCUTjinchengli** [comment]
您好，test.json中categories的1-233为base类，234-466为novel类，novel 类别的物体按照test.json中categories对应的id提交即可。
例如，给定3个bbox的特征，您预测的类别分别为”古董文玩“，”古董文玩“，”女士泳衣“，那您提交的json文件的三条数据中的category_id为别为1，1，466。提交的json文件如下  [{'image_id': xxx, 'category_id': 1, 'bbox': [xxx, xxx, xxx, xxx], 'score': xxx}, {'image_id': xxx, 'category_id': 1, 'bbox': [xxx, xxx, xxx, xxx], 'score': xxx}, {'image_id': xxx, 'category_id': 466, 'bbox': [xxx, xxx, xxx, xxx], 'score': xxx}]

**Comment by msbrm** [comment]
您好，“novel 类别的物体按照test.json中categories对应的id提交即可” 这里的意思我了解了。

**Comment by msbrm** [comment]
您好，“novel 类别的物体按照test.json中categories对应的id提交即可。” 是需要通过 base 类别部分学习到 检测目标到中文语义的转义能力，再通过这种能力对 novel 部分检测到的目标转义到中文，对应到 novel 类别中的中文，得到 category_id 并提交吗？
