### ISSUE TITLE
用户无法注册

### ISSUE THREAD

**Issue by Windsrain** [360CVGroup/OVD_Contest#6]
![18W1ZR_XOU7HW7B %GVA93C](https://user-images.githubusercontent.com/43723173/236770894-2740e109-2090-4d76-9a0d-89a35a25cc68.png)
![O1$QHE5FDVFMU7 B9QV5Q2J](https://user-images.githubusercontent.com/43723173/236770950-3742c4f3-abdd-423c-a456-328b96ad0432.png)
点击链接后显示表单无法访问，请问该如何解决？

**Comment by binwang777** [comment]
你好，目前已经恢复访问
