### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by thunderstudying** [360CVGroup/OVD_Contest#9]
先前注册的时候信息提交错误，需要重新注册，还是后续可以修改呢？

**Comment by binwang777** [comment]
你好，现在一个邮箱只允许一个uuid，你可以更改邮箱进行重新注册，同时修正提交的信息。或者把你的邮箱信息留下，后台进行删除，便可以重新注册

**Comment by thunderstudying** [comment]
好的，麻烦您在后台删除

邮箱是252086746@qq.com
